sonar.projectKey=bel001_BarberCLoud
sonar.organization=bel001

sonar.projectName=BarberCLoud
sonar.projectVersion=1.0

sonar.sources=backend/src,frontend
sonar.tests=backend/test
sonar.test.inclusions=backend/test/**/*.js
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,iac/**,docs/**,backend/src/local-server.js
sonar.coverage.exclusions=frontend/**,backend/src/local-server.js,backend/src/lib/db.js
sonar.cpd.exclusions=frontend/**/*.html

sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
