apiVersion: 1

contactPoints:
  - orgId: 1
    name: BarberCloud Webhook
    receivers:
      - uid: barbercloud_webhook
        type: webhook
        disableResolveMessage: false
        settings:
          url: http://backend:3001/alerts/grafana
          httpMethod: POST
          authorization_scheme: Bearer
          authorization_credentials: $GRAFANA_WEBHOOK_TOKEN
          maxAlerts: "10"
