apiVersion: 1

groups:
  - orgId: 1
    name: BarberCloud CPU
    folder: BarberCloud
    interval: 10s
    rules:
      - uid: barbercloud_cpu_backend_50
        title: CPU backend superior al 50 por ciento
        condition: C
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 60
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              expr: sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service="backend"}[1m])) * 100
              instant: false
              intervalMs: 1000
              legendFormat: backend
              maxDataPoints: 43200
              range: true
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions: []
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              reducer: last
              refId: B
              type: reduce
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 50
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              refId: C
              type: threshold
        dashboardUid: barbercloud-observabilidad
        panelId: 1
        noDataState: NoData
        execErrState: Error
        for: 30s
        annotations:
          description: El contenedor backend superó el 50 por ciento de CPU durante 30 segundos.
          summary: CPU elevada en BarberCloud backend.
        labels:
          severity: warning
          service: backend
